### PR TITLE
[STRAIGHT-32] mycelium adapter ssl verification

### PR DESCRIPTION
**Pull request by AlexanderPavlenko**
requires testing in the both mainnet/testnet modes on staging

### CODE REVIEW

**Comment by dsnipe** [comment]
It's still open source, maybe we shouldn't use internal tickets names in commits comments?

**Comment by AlexanderPavlenko** [comment]
Why not?

**Comment by dsnipe** [comment]
For external people it's very cryptic names, meaningless.

**Comment by snitko** [comment]
I also agree on this one and I told you so, @AlexanderPavlenko
Let's not use Jira tickets names and instead use something meaningful for open source projects.

I know you think not many people use or watch Straight now, but cryptic ticket names only contribute to that situation and don't help.

**Pull request merged**
